/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Danie
 */
public class InicialView extends JFrame {

    /**
     * Creates new form InicialView
     */
    public InicialView() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        caixaMenu = new javax.swing.JMenu();
        cadastrosMenu = new javax.swing.JMenu();
        caixasMenuItem = new javax.swing.JMenuItem();
        funcionariosMenuItem = new javax.swing.JMenuItem();
        produtosMenuItem = new javax.swing.JMenuItem();
        relatoriosMenu = new javax.swing.JMenu();
        vendasMenuItem = new javax.swing.JMenuItem();
        estoqueMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        desktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(160, -30, 2, 2);

        caixaMenu.setMnemonic('f');
        caixaMenu.setText("Caixa");
        caixaMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                caixaMenuMenuSelected(evt);
            }
        });
        caixaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaMenuActionPerformed(evt);
            }
        });
        caixaMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caixaMenuKeyPressed(evt);
            }
        });
        menuBar.add(caixaMenu);

        cadastrosMenu.setMnemonic('e');
        cadastrosMenu.setText("Cadastros");

        caixasMenuItem.setMnemonic('t');
        caixasMenuItem.setText("Caixas");
        caixasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixasMenuItemActionPerformed(evt);
            }
        });
        cadastrosMenu.add(caixasMenuItem);

        funcionariosMenuItem.setMnemonic('y');
        funcionariosMenuItem.setText("Funcionarios");
        funcionariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosMenuItemActionPerformed(evt);
            }
        });
        cadastrosMenu.add(funcionariosMenuItem);

        produtosMenuItem.setMnemonic('p');
        produtosMenuItem.setText("Produtos");
        produtosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosMenuItemActionPerformed(evt);
            }
        });
        cadastrosMenu.add(produtosMenuItem);

        menuBar.add(cadastrosMenu);

        relatoriosMenu.setMnemonic('h');
        relatoriosMenu.setText("Relatorios");

        vendasMenuItem.setMnemonic('c');
        vendasMenuItem.setText("Vendas");
        vendasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasMenuItemActionPerformed(evt);
            }
        });
        relatoriosMenu.add(vendasMenuItem);

        estoqueMenuItem.setMnemonic('a');
        estoqueMenuItem.setText("Estoque");
        estoqueMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueMenuItemActionPerformed(evt);
            }
        });
        relatoriosMenu.add(estoqueMenuItem);

        menuBar.add(relatoriosMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixasMenuItemActionPerformed
        CaixasView caixaView = new CaixasView();
        caixaView.setVisible(true);
        this.desktopPane.removeAll();
        this.desktopPane.add(caixaView);

    }//GEN-LAST:event_caixasMenuItemActionPerformed

    private void funcionariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosMenuItemActionPerformed
        PessoasView funcionariosView = new PessoasView();
        funcionariosView.setVisible(true);
        this.desktopPane.removeAll();
        this.desktopPane.add(funcionariosView);
    }//GEN-LAST:event_funcionariosMenuItemActionPerformed

    private void caixaMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaMenuKeyPressed

    private void produtosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosMenuItemActionPerformed
      ProdutosView produtosView = new ProdutosView();
        produtosView.setVisible(true);
        this.desktopPane.removeAll();
        this.desktopPane.add(produtosView);       
    }//GEN-LAST:event_produtosMenuItemActionPerformed

    private void caixaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaMenuActionPerformed
   
    }//GEN-LAST:event_caixaMenuActionPerformed

    private void caixaMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_caixaMenuMenuSelected
       VendasView caixaPrincipalView = new VendasView();
       caixaPrincipalView.setVisible(true);
        this.desktopPane.removeAll();
        this.desktopPane.add(caixaPrincipalView);
    }//GEN-LAST:event_caixaMenuMenuSelected

    private void vendasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasMenuItemActionPerformed
           RelatoriosVendasView relatoriosVendasView = new RelatoriosVendasView();
       relatoriosVendasView.setVisible(true);
        this.desktopPane.removeAll();
        this.desktopPane.add(relatoriosVendasView);
    }//GEN-LAST:event_vendasMenuItemActionPerformed

    private void estoqueMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueMenuItemActionPerformed
              
        RelatoriosEstoqueView relatoriosEstoqueView = new RelatoriosEstoqueView();
       relatoriosEstoqueView.setVisible(true);
        this.desktopPane.removeAll();
        this.desktopPane.add(relatoriosEstoqueView);
    }//GEN-LAST:event_estoqueMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadastrosMenu;
    private javax.swing.JMenu caixaMenu;
    private javax.swing.JMenuItem caixasMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem estoqueMenuItem;
    private javax.swing.JMenuItem funcionariosMenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem produtosMenuItem;
    private javax.swing.JMenu relatoriosMenu;
    private javax.swing.JMenuItem vendasMenuItem;
    // End of variables declaration//GEN-END:variables

}
