/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ItemvendaJpaController;
import controller.ProdutoJpaController;
import controller.VendasJpaController;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.domain.Itemvenda;
import model.domain.Produto;
import model.domain.Vendas;

/**
 *
 * @author Danie
 */
public class VendasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Teste
     */
    
    private ProdutoJpaController produtoJpaController;
    private VendasJpaController vendasJpaController;
    private ItemvendaJpaController itemvendaJpaController;

    public VendasView() {
          produtoJpaController = new ProdutoJpaController();
          vendasJpaController = new VendasJpaController();
          itemvendaJpaController = new ItemvendaJpaController();
          initComponents();
    }
        
    public ProdutoJpaController getProdutoscontroller() {
        return produtoJpaController;
    }

    public VendasJpaController getVendasJpaController() {
        return vendasJpaController;
    }

    public ItemvendaJpaController getItemvendaJpaController() {
        return itemvendaJpaController;
    }
    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        textDescricao = new javax.swing.JTextField();
        textUnidade = new javax.swing.JTextField();
        textCodigoBarra = new javax.swing.JTextField();
        textValorTotalCompra = new javax.swing.JTextField();
        textQuantidade = new javax.swing.JTextField();
        textValorUniario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textValorTotalItem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FRENTE DE CAIXA");

        textDescricao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textUnidade.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textUnidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textUnidade.setText("UN");

        textCodigoBarra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoBarraActionPerformed(evt);
            }
        });
        textCodigoBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCodigoBarraKeyPressed(evt);
            }
        });

        textValorTotalCompra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textValorTotalCompra.setForeground(new java.awt.Color(255, 0, 51));
        textValorTotalCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValorTotalCompra.setText("0.00");

        textQuantidade.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textQuantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textQuantidade.setText("1");
        textQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textQuantidadeKeyPressed(evt);
            }
        });

        textValorUniario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textValorUniario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValorUniario.setText("0");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${itemvendaJpaController.itemVendas}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeProduto}"));
        columnBinding.setColumnName("Nome Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unidadeProduto}"));
        columnBinding.setColumnName("Unidade Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidadeProduto}"));
        columnBinding.setColumnName("Quantidade Produto");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorUnitario}"));
        columnBinding.setColumnName("Valor Unitario");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorTotal}"));
        columnBinding.setColumnName("Valor Total");
        columnBinding.setColumnClass(Double.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        textValorTotalItem.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textValorTotalItem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValorTotalItem.setText("0.00");
        textValorTotalItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorTotalItemActionPerformed(evt);
            }
        });
        textValorTotalItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textValorTotalItemKeyPressed(evt);
            }
        });

        jButton1.setText("Nova venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Receber a vista");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Receber com cartão");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Codigo do produto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Descrição do produto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Unidade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Valor Unitário");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Valor Total Item");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Valor total da venda");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Lista de produtos");

        jButton4.setText("Calcular Balança");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textCodigoBarra, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textValorUniario, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(textUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(24, 24, 24))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(textValorTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton5)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(286, 286, 286)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textValorTotalCompra)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(textValorUniario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(3, 3, 3)
                        .addComponent(textValorTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textValorTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(25, 25, 25))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textValorTotalItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorTotalItemActionPerformed
        
    }//GEN-LAST:event_textValorTotalItemActionPerformed

    private void textCodigoBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoBarraKeyPressed
     if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      Produto prod = this.produtoJpaController.findProduto(Integer.valueOf(this.textCodigoBarra.getText()));
      this.textCodigoBarra.setText(String.valueOf(prod.getIdProduto()));
      this.textDescricao.setText(prod.getNomeProduto());
      this.textUnidade.setText(prod.getUnidadeProduto());
      this.textValorUniario.setText(String.valueOf(prod.getValorPoduto()));
      this.textValorTotalItem.setText(String.valueOf(Double.valueOf(this.textQuantidade.getText()) * prod.getValorPoduto()));
      if(prod.getUnidadeProduto().equals("KG")){
          System.out.print(prod.getUnidadeProduto());
          this.jButton4.setEnabled(true);
      } else {
          this.jButton4.setEnabled(false);
      }
     }
    }//GEN-LAST:event_textCodigoBarraKeyPressed

    private void textQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textQuantidadeKeyPressed
         if(!this.textQuantidade.getText().isEmpty()) {
          this.textValorTotalItem.setText(String.valueOf(Double.valueOf(this.textQuantidade.getText()) * Double.valueOf(this.textValorUniario.getText())));
         }
    }//GEN-LAST:event_textQuantidadeKeyPressed

    private void textValorTotalItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textValorTotalItemKeyPressed
     if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
         
      Produto prod = this.produtoJpaController.findProduto(Integer.valueOf(this.textCodigoBarra.getText()));
         try {
            this.itemvendaJpaController.create(new Itemvenda(Integer.valueOf(this.textCodigoBarra.getText()), this.vendasJpaController.getVendasCount(), Double.valueOf(this.textQuantidade.getText()), Double.valueOf(this.textValorTotalItem.getText()), prod.getNomeProduto(), prod.getValorPoduto(), prod.getUnidadeProduto()));
            this.textCodigoBarra.setText(null);
            this.textDescricao.setText(null);
            this.textUnidade.setText(null);
            this.textValorUniario.setText(null);
            this.textValorTotalItem.setText(null);
            this.itemvendaJpaController.limparLista();
            this.jButton2.setEnabled(true);
            this.jButton3.setEnabled(true);
            this.textValorTotalCompra.setText(String.valueOf(this.itemvendaJpaController.getValorItems()));
          } catch (Exception ex) {
             Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
         }
         
     }
    }//GEN-LAST:event_textValorTotalItemKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        double valorTroco;
        double valorPago = Double.valueOf(JOptionPane.showInputDialog(null, "Qual o valor que deseja receber? O valor a ser pago é R$"+this.textValorTotalCompra.getText()));
        valorTroco = Double.valueOf(this.textValorTotalCompra.getText()) - valorPago;
        JOptionPane.showMessageDialog(null, "Valor do troco: R$"+ valorTroco);
        try {
            this.vendasJpaController.create(new Vendas(1, Double.valueOf(this.textValorTotalCompra.getText()), Double.valueOf(valorPago), Double.valueOf(valorTroco), "Dinheiro", new Date()));
            this.textCodigoBarra.setText(null);
            this.textDescricao.setText(null);
            this.textUnidade.setText(null);
            this.textValorUniario.setText(null);
            this.textValorTotalItem.setText(null);
            this.itemvendaJpaController.limparLista();
            this.textValorTotalCompra.setText(null);
            this.jButton2.setEnabled(false);
            this.jButton3.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            this.vendasJpaController.create(new Vendas(1, Double.valueOf(this.textValorTotalCompra.getText()), Double.valueOf(this.textValorTotalCompra.getText()), Double.valueOf(0), "Cartão", new Date()));
            JOptionPane.showMessageDialog(null, "Venda com cartão realizada com sucesso");
            this.textCodigoBarra.setText(null);
            this.textDescricao.setText(null);
            this.textUnidade.setText(null);
            this.textValorUniario.setText(null);
            this.textValorTotalItem.setText(null);
            this.itemvendaJpaController.limparLista();
            this.textValorTotalCompra.setText(null);
            this.jButton2.setEnabled(false);
            this.jButton3.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.vendasJpaController.create(new Vendas(1, Double.valueOf(0), Double.valueOf(0), Double.valueOf(0), "Cartão", new Date()));
        } catch (Exception ex) {
            Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoBarraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double valorBalanca = Math.round(Math.random() * 10);
        this.textQuantidade.setText(String.valueOf(valorBalanca));
        JOptionPane.showMessageDialog(null, "Kilos pesados na balança: " + valorBalanca);
        this.textValorTotalItem.setText(String.valueOf(Double.valueOf(this.textQuantidade.getText()) * Double.valueOf(this.textValorUniario.getText())));
        this.jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          Produto prod = this.produtoJpaController.findProduto(Integer.valueOf(this.textCodigoBarra.getText()));
         try {
            this.itemvendaJpaController.edit(new Itemvenda(Integer.valueOf(this.textCodigoBarra.getText()), this.vendasJpaController.getVendasLastId(), Double.valueOf(this.textQuantidade.getText()), Double.valueOf(this.textValorTotalItem.getText()), prod.getNomeProduto(), prod.getValorPoduto(), prod.getUnidadeProduto()));
            this.textCodigoBarra.setText(null);
            this.textDescricao.setText(null);
            this.textUnidade.setText(null);
            this.textValorUniario.setText(null);
            this.textValorTotalItem.setText(null);
            this.itemvendaJpaController.limparLista();
            this.jButton2.setEnabled(true);
            this.jButton3.setEnabled(true);
            this.textValorTotalCompra.setText(String.valueOf(this.itemvendaJpaController.getValorItems()));
          } catch (Exception ex) {
             Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textCodigoBarra;
    private javax.swing.JTextField textDescricao;
    private javax.swing.JTextField textQuantidade;
    private javax.swing.JTextField textUnidade;
    private javax.swing.JTextField textValorTotalCompra;
    private javax.swing.JTextField textValorTotalItem;
    private javax.swing.JTextField textValorUniario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
